In [55]:
import numpy as np
def column_input_splitter(file)-> tuple:
    data = open(file, 'r').read().split("\n")
    column1 = []
    column2 = []

    for line in data:

        col1, col2 = line.split()

        column1.append(int(col1))
        column2.append(int(col2))
    
    return column1, column2

col1, col2 = column_input_splitter("1.txt")
col1.sort()
col2.sort()

# Part1

## Base solution

In [56]:
total_distance = 0
for i in range(len(col1)):
    distance = col2[i] - col1[i]
    total_distance = total_distance + abs(distance)

total_distance

2742123

## Numpy solution

In [54]:
array1 = np.array(col1)
array2 = np.array(col2)

np.abs(array2 - array1).sum()

2742123

# Part 2

In [89]:
import numpy as np
def column_input_splitter(file)-> tuple:
    data = open(file, 'r').read().split("\n")
    column1 = []
    column2 = []

    for line in data:

        col1, col2 = line.split()

        column1.append(int(col1))
        column2.append(int(col2))
    
    return column1, column2

col1, col2 = column_input_splitter("1.txt")

## Base solution

In [98]:
total_score = 0

for i in array1:
    score = (i == array2).sum() * i 
    total_score = total_score + score
total_score

array([21328497])

## Numpy solution

In [92]:
array1 = np.array(col1).reshape(-1, 1) # Reshape to column vector instead of row
array2 = np.array(col2)
total_score = np.sum((array1 == array2) * array1)

total_score

21328497

In [68]:
array1 = np.array(col1)
array2 = np.array(col2)

array1 == array2

array([False, False, False, False, False,  True])

In [77]:
array1[:,None]

array([[3],
       [4],
       [2],
       [1],
       [3],
       [3]])

In [86]:
array1.reshape(-1, 1)

TypeError: 'inplace' is an invalid keyword argument for this function

In [85]:
array1

array([3, 4, 2, 1, 3, 3])

In [103]:
np.loadtxt("sample.txt", dtype=np.int64)

array([[3, 4],
       [4, 3],
       [2, 5],
       [1, 3],
       [3, 9],
       [3, 3]])